meta_product_name: "FartSquare"
meta_title: "FartSquare - Faça o número 2 em qualquer lugar, como se estivesse em casa"
meta_description: "FartSquare é uma plataforma revolucionária para que quando você vá usar o banheiro fora de casa, tenha a melhor experiência possível"
meta_image: "toiler_paper.png" # should exist in `app/assets/images/`
twitter_account: "@fartsquare"   # required for Twitter Cards
