name: Ruby

on:
  [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: andrewmcodes-archive/rubocop-linter-action@v3.3.0
      - name: Set up Ruby
        uses: ruby/setup-ruby@477b21f02be01bcb8030d50f37cfec92bfa615b6
        with:
          ruby-version: 2.7.3
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rake              
      - name: Rubocop
        run: rubocop --format simple



